# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171102_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 5, 8, 52, 78256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 5, 8, 52, 77461, tzinfo=utc)),
        ),
    ]
